
import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'nl' | 'sv' | 'da' | 'no' | 'fi' | 'pl' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.mission': 'Mission',
    'nav.features': 'Features',
    'nav.services': 'Services',
    'nav.community': 'Community',
    'nav.dashboard': 'Dashboard',
    'nav.signIn': 'Sign In',
    'nav.getStarted': 'Get Started',
    'hero.title1': 'Your Global',
    'hero.title2': 'Wellness Journey',
    'hero.title3': 'Starts Here',
    'hero.subtitle': 'Connect with health services, resources, and communities that promote mental and physical wellbeing across borders. Join a global movement towards better health for everyone, everywhere.',
    'hero.startJourney': 'Start Your Wellness Journey',
    'hero.learnMore': 'Learn More',
    'stats.members': 'Global Members',
    'stats.countries': 'Countries',
    'stats.support': 'Support',
    'mission.title': 'Our Mission',
    'mission.description': 'At Borderless Wellbeing, we believe that access to mental and physical health resources should know no boundaries. Our mission is to create a global ecosystem where individuals from every corner of the world can connect, heal, and thrive together.',
    'features.title': 'Wellness Without Borders',
    'features.subtitle': 'Discover our comprehensive suite of features designed to support your journey towards better health and wellbeing, connecting you with resources and communities from around the globe.',
    'footer.company': 'Borderless Wellbeing',
    'footer.description': 'Connecting global communities to promote mental and physical wellbeing across all borders. Your health journey knows no boundaries.'
  },
  es: {
    'nav.home': 'Inicio',
    'nav.mission': 'Misión',
    'nav.features': 'Características',
    'nav.services': 'Servicios',
    'nav.community': 'Comunidad',
    'nav.dashboard': 'Panel',
    'nav.signIn': 'Iniciar Sesión',
    'nav.getStarted': 'Comenzar',
    'hero.title1': 'Tu Viaje Global',
    'hero.title2': 'de Bienestar',
    'hero.title3': 'Comienza Aquí',
    'hero.subtitle': 'Conéctate con servicios de salud, recursos y comunidades que promueven el bienestar mental y físico sin fronteras.',
    'hero.startJourney': 'Comienza Tu Viaje de Bienestar',
    'hero.learnMore': 'Saber Más',
    'stats.members': 'Miembros Globales',
    'stats.countries': 'Países',
    'stats.support': 'Soporte',
    'mission.title': 'Nuestra Misión',
    'mission.description': 'En Borderless Wellbeing, creemos que el acceso a recursos de salud mental y física no debe tener fronteras.',
    'features.title': 'Bienestar Sin Fronteras',
    'features.subtitle': 'Descubre nuestro conjunto completo de características diseñadas para apoyar tu viaje hacia una mejor salud y bienestar.',
    'footer.company': 'Bienestar Sin Fronteras',
    'footer.description': 'Conectando comunidades globales para promover el bienestar mental y físico sin fronteras.'
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.mission': 'Mission',
    'nav.features': 'Fonctionnalités',
    'nav.services': 'Services',
    'nav.community': 'Communauté',
    'nav.dashboard': 'Tableau de Bord',
    'nav.signIn': 'Se Connecter',
    'nav.getStarted': 'Commencer',
    'hero.title1': 'Votre Voyage',
    'hero.title2': 'de Bien-être Global',
    'hero.title3': 'Commence Ici',
    'hero.subtitle': 'Connectez-vous avec des services de santé, des ressources et des communautés qui promeuvent le bien-être mental et physique sans frontières.',
    'hero.startJourney': 'Commencez Votre Voyage de Bien-être',
    'hero.learnMore': 'En Savoir Plus',
    'stats.members': 'Membres Mondiaux',
    'stats.countries': 'Pays',
    'stats.support': 'Support',
    'mission.title': 'Notre Mission',
    'mission.description': 'Chez Borderless Wellbeing, nous croyons que l\'accès aux ressources de santé mentale et physique ne devrait avoir aucune frontière.',
    'features.title': 'Bien-être Sans Frontières',
    'features.subtitle': 'Découvrez notre suite complète de fonctionnalités conçues pour soutenir votre voyage vers une meilleure santé et bien-être.',
    'footer.company': 'Bien-être Sans Frontières',
    'footer.description': 'Connecter les communautés mondiales pour promouvoir le bien-être mental et physique sans frontières.'
  },
  de: {
    'nav.home': 'Startseite',
    'nav.mission': 'Mission',
    'nav.features': 'Funktionen',
    'nav.services': 'Dienstleistungen',
    'nav.community': 'Gemeinschaft',
    'nav.dashboard': 'Dashboard',
    'nav.signIn': 'Anmelden',
    'nav.getStarted': 'Loslegen',
    'hero.title1': 'Ihre Globale',
    'hero.title2': 'Wellness-Reise',
    'hero.title3': 'Beginnt Hier',
    'hero.subtitle': 'Verbinden Sie sich mit Gesundheitsdiensten, Ressourcen und Gemeinschaften, die geistiges und körperliches Wohlbefinden grenzüberschreitend fördern.',
    'hero.startJourney': 'Beginnen Sie Ihre Wellness-Reise',
    'hero.learnMore': 'Mehr Erfahren',
    'stats.members': 'Globale Mitglieder',
    'stats.countries': 'Länder',
    'stats.support': 'Support',
    'mission.title': 'Unsere Mission',
    'mission.description': 'Bei Borderless Wellbeing glauben wir, dass der Zugang zu geistigen und körperlichen Gesundheitsressourcen keine Grenzen haben sollte.',
    'features.title': 'Wellness Ohne Grenzen',
    'features.subtitle': 'Entdecken Sie unser umfassendes Funktionspaket, das darauf ausgelegt ist, Ihre Reise zu besserer Gesundheit und Wohlbefinden zu unterstützen.',
    'footer.company': 'Wellness Ohne Grenzen',
    'footer.description': 'Verbindung globaler Gemeinschaften zur Förderung des geistigen und körperlichen Wohlbefindens ohne Grenzen.'
  },
  it: {
    'nav.home': 'Home',
    'nav.mission': 'Missione',
    'nav.features': 'Caratteristiche',
    'nav.services': 'Servizi',
    'nav.community': 'Comunità',
    'nav.dashboard': 'Dashboard',
    'nav.signIn': 'Accedi',
    'nav.getStarted': 'Inizia',
    'hero.title1': 'Il Tuo Viaggio',
    'hero.title2': 'di Benessere Globale',
    'hero.title3': 'Inizia Qui',
    'hero.subtitle': 'Connettiti con servizi sanitari, risorse e comunità che promuovono il benessere mentale e fisico oltre i confini.',
    'hero.startJourney': 'Inizia Il Tuo Viaggio di Benessere',
    'hero.learnMore': 'Scopri di Più',
    'stats.members': 'Membri Globali',
    'stats.countries': 'Paesi',
    'stats.support': 'Supporto',
    'mission.title': 'La Nostra Missione',
    'mission.description': 'In Borderless Wellbeing, crediamo che l\'accesso alle risorse di salute mentale e fisica non dovrebbe avere confini.',
    'features.title': 'Benessere Senza Confini',
    'features.subtitle': 'Scopri la nostra suite completa di funzionalità progettate per supportare il tuo viaggio verso una migliore salute e benessere.',
    'footer.company': 'Benessere Senza Confini',
    'footer.description': 'Connettere comunità globali per promuovere il benessere mentale e fisico senza confini.'
  },
  pt: {
    'nav.home': 'Início',
    'nav.mission': 'Missão',
    'nav.features': 'Recursos',
    'nav.services': 'Serviços',
    'nav.community': 'Comunidade',
    'nav.dashboard': 'Painel',
    'nav.signIn': 'Entrar',
    'nav.getStarted': 'Começar',
    'hero.title1': 'Sua Jornada',
    'hero.title2': 'de Bem-estar Global',
    'hero.title3': 'Começa Aqui',
    'hero.subtitle': 'Conecte-se com serviços de saúde, recursos e comunidades que promovem bem-estar mental e físico além das fronteiras.',
    'hero.startJourney': 'Comece Sua Jornada de Bem-estar',
    'hero.learnMore': 'Saiba Mais',
    'stats.members': 'Membros Globais',
    'stats.countries': 'Países',
    'stats.support': 'Suporte',
    'mission.title': 'Nossa Missão',
    'mission.description': 'Na Borderless Wellbeing, acreditamos que o acesso a recursos de saúde mental e física não deve ter fronteiras.',
    'features.title': 'Bem-estar Sem Fronteiras',
    'features.subtitle': 'Descubra nosso conjunto abrangente de recursos projetados para apoiar sua jornada rumo a uma melhor saúde e bem-estar.',
    'footer.company': 'Bem-estar Sem Fronteiras',
    'footer.description': 'Conectando comunidades globais para promover bem-estar mental e físico sem fronteiras.'
  },
  nl: {
    'nav.home': 'Home',
    'nav.mission': 'Missie',
    'nav.features': 'Functies',
    'nav.services': 'Diensten',
    'nav.community': 'Gemeenschap',
    'nav.dashboard': 'Dashboard',
    'nav.signIn': 'Inloggen',
    'nav.getStarted': 'Beginnen',
    'hero.title1': 'Uw Wereldwijde',
    'hero.title2': 'Wellness Reis',
    'hero.title3': 'Begint Hier',
    'hero.subtitle': 'Verbind met gezondheidsdiensten, middelen en gemeenschappen die mentaal en fysiek welzijn over grenzen heen bevorderen.',
    'hero.startJourney': 'Begin Uw Wellness Reis',
    'hero.learnMore': 'Meer Leren',
    'stats.members': 'Wereldwijde Leden',
    'stats.countries': 'Landen',
    'stats.support': 'Ondersteuning',
    'mission.title': 'Onze Missie',
    'mission.description': 'Bij Borderless Wellbeing geloven we dat toegang tot mentale en fysieke gezondheidsmiddelen geen grenzen zou moeten hebben.',
    'features.title': 'Wellness Zonder Grenzen',
    'features.subtitle': 'Ontdek ons uitgebreide pakket functies ontworpen om uw reis naar betere gezondheid en welzijn te ondersteunen.',
    'footer.company': 'Wellness Zonder Grenzen',
    'footer.description': 'Wereldwijde gemeenschappen verbinden om mentaal en fysiek welzijn zonder grenzen te bevorderen.'
  },
  sv: {
    'nav.home': 'Hem',
    'nav.mission': 'Mission',
    'nav.features': 'Funktioner',
    'nav.services': 'Tjänster',
    'nav.community': 'Gemenskap',
    'nav.dashboard': 'Dashboard',
    'nav.signIn': 'Logga In',
    'nav.getStarted': 'Kom Igång',
    'hero.title1': 'Din Globala',
    'hero.title2': 'Hälsoresan',
    'hero.title3': 'Börjar Här',
    'hero.subtitle': 'Anslut till hälsotjänster, resurser och gemenskaper som främjar mental och fysisk välbefinnande över gränser.',
    'hero.startJourney': 'Börja Din Hälsoresan',
    'hero.learnMore': 'Lär Dig Mer',
    'stats.members': 'Globala Medlemmar',
    'stats.countries': 'Länder',
    'stats.support': 'Support',
    'mission.title': 'Vårt Uppdrag',
    'mission.description': 'På Borderless Wellbeing tror vi att tillgång till mentala och fysiska hälsoresurser inte ska ha några gränser.',
    'features.title': 'Hälsa Utan Gränser',
    'features.subtitle': 'Upptäck vårt omfattande paket med funktioner utformade för att stödja din resa mot bättre hälsa och välbefinnande.',
    'footer.company': 'Hälsa Utan Gränser',
    'footer.description': 'Förbinder globala gemenskaper för att främja mental och fysisk hälsa utan gränser.'
  },
  da: {
    'nav.home': 'Hjem',
    'nav.mission': 'Mission',
    'nav.features': 'Funktioner',
    'nav.services': 'Tjenester',
    'nav.community': 'Fællesskab',
    'nav.dashboard': 'Dashboard',
    'nav.signIn': 'Log Ind',
    'nav.getStarted': 'Kom I Gang',
    'hero.title1': 'Din Globale',
    'hero.title2': 'Wellness Rejse',
    'hero.title3': 'Starter Her',
    'hero.subtitle': 'Forbind med sundhedstjenester, ressourcer og fællesskaber, der fremmer mental og fysisk velvære på tværs af grænser.',
    'hero.startJourney': 'Start Din Wellness Rejse',
    'hero.learnMore': 'Lær Mere',
    'stats.members': 'Globale Medlemmer',
    'stats.countries': 'Lande',
    'stats.support': 'Support',
    'mission.title': 'Vores Mission',
    'mission.description': 'Hos Borderless Wellbeing tror vi, at adgang til mentale og fysiske sundhedsressourcer ikke bør have grænser.',
    'features.title': 'Wellness Uden Grænser',
    'features.subtitle': 'Opdag vores omfattende pakke af funktioner designet til at støtte din rejse mod bedre sundhed og velvære.',
    'footer.company': 'Wellness Uden Grænser',
    'footer.description': 'Forbinder globale fællesskaber for at fremme mental og fysisk velvære uden grænser.'
  },
  no: {
    'nav.home': 'Hjem',
    'nav.mission': 'Misjon',
    'nav.features': 'Funksjoner',
    'nav.services': 'Tjenester',
    'nav.community': 'Fellesskap',
    'nav.dashboard': 'Dashboard',
    'nav.signIn': 'Logg Inn',
    'nav.getStarted': 'Kom I Gang',
    'hero.title1': 'Din Globale',
    'hero.title2': 'Wellness Reise',
    'hero.title3': 'Starter Her',
    'hero.subtitle': 'Koble til helsetjenester, ressurser og fellesskap som fremmer mental og fysisk velvære på tvers av grenser.',
    'hero.startJourney': 'Start Din Wellness Reise',
    'hero.learnMore': 'Lær Mer',
    'stats.members': 'Globale Medlemmer',
    'stats.countries': 'Land',
    'stats.support': 'Støtte',
    'mission.title': 'Vårt Oppdrag',
    'mission.description': 'Hos Borderless Wellbeing tror vi at tilgang til mentale og fysiske helseressurser ikke bør ha grenser.',
    'features.title': 'Wellness Uten Grenser',
    'features.subtitle': 'Oppdag vår omfattende pakke med funksjoner designet for å støtte din reise mot bedre helse og velvære.',
    'footer.company': 'Wellness Uten Grenser',
    'footer.description': 'Kobler globale fellesskap for å fremme mental og fysisk velvære uten grenser.'
  },
  fi: {
    'nav.home': 'Koti',
    'nav.mission': 'Missio',
    'nav.features': 'Ominaisuudet',
    'nav.services': 'Palvelut',
    'nav.community': 'Yhteisö',
    'nav.dashboard': 'Kojelauta',
    'nav.signIn': 'Kirjaudu',
    'nav.getStarted': 'Aloita',
    'hero.title1': 'Sinun Globaali',
    'hero.title2': 'Hyvinvointi Matka',
    'hero.title3': 'Alkaa Täältä',
    'hero.subtitle': 'Yhdistä terveyspalveluihin, resursseihin ja yhteisöihin, jotka edistävät henkistä ja fyysistä hyvinvointia rajojen yli.',
    'hero.startJourney': 'Aloita Hyvinvointi Matkasi',
    'hero.learnMore': 'Lue Lisää',
    'stats.members': 'Globaalit Jäsenet',
    'stats.countries': 'Maat',
    'stats.support': 'Tuki',
    'mission.title': 'Missiomme',
    'mission.description': 'Borderless Wellbeingissä uskomme, että pääsy henkisiin ja fyysisiin terveysresursseihin ei saisi olla rajoitettu.',
    'features.title': 'Hyvinvointi Ilman Rajoja',
    'features.subtitle': 'Löydä kattava ominaisuuspakettimme, joka on suunniteltu tukemaan matkaasi kohti parempaa terveyttä ja hyvinvointia.',
    'footer.company': 'Hyvinvointi Ilman Rajoja',
    'footer.description': 'Yhdistää maailmanlaajuisia yhteisöjä edistämään henkistä ja fyysistä hyvinvointia ilman rajoja.'
  },
  pl: {
    'nav.home': 'Strona Główna',
    'nav.mission': 'Misja',
    'nav.features': 'Funkcje',
    'nav.services': 'Usługi',
    'nav.community': 'Społeczność',
    'nav.dashboard': 'Panel',
    'nav.signIn': 'Zaloguj',
    'nav.getStarted': 'Zacznij',
    'hero.title1': 'Twoja Globalna',
    'hero.title2': 'Podróż Wellness',
    'hero.title3': 'Zaczyna Się Tutaj',
    'hero.subtitle': 'Połącz się z usługami zdrowotnymi, zasobami i społecznościami, które promują dobrostan psychiczny i fizyczny ponad granicami.',
    'hero.startJourney': 'Rozpocznij Swoją Podróż Wellness',
    'hero.learnMore': 'Dowiedz Się Więcej',
    'stats.members': 'Globalni Członkowie',
    'stats.countries': 'Kraje',
    'stats.support': 'Wsparcie',
    'mission.title': 'Nasza Misja',
    'mission.description': 'W Borderless Wellbeing wierzymy, że dostęp do zasobów zdrowia psychicznego i fizycznego nie powinien mieć granic.',
    'features.title': 'Wellness Bez Granic',
    'features.subtitle': 'Odkryj nasz kompleksowy pakiet funkcji zaprojektowanych, aby wspierać Twoją podróż ku lepszemu zdrowiu i dobrostanowi.',
    'footer.company': 'Wellness Bez Granic',
    'footer.description': 'Łączenie globalnych społeczności w celu promowania dobrostanu psychicznego i fizycznego bez granic.'
  },
  ru: {
    'nav.home': 'Главная',
    'nav.mission': 'Миссия',
    'nav.features': 'Возможности',
    'nav.services': 'Услуги',
    'nav.community': 'Сообщество',
    'nav.dashboard': 'Панель',
    'nav.signIn': 'Войти',
    'nav.getStarted': 'Начать',
    'hero.title1': 'Ваше Глобальное',
    'hero.title2': 'Путешествие Wellness',
    'hero.title3': 'Начинается Здесь',
    'hero.subtitle': 'Подключитесь к медицинским услугам, ресурсам и сообществам, которые способствуют психическому и физическому благополучию через границы.',
    'hero.startJourney': 'Начните Ваше Путешествие Wellness',
    'hero.learnMore': 'Узнать Больше',
    'stats.members': 'Глобальные Участники',
    'stats.countries': 'Страны',
    'stats.support': 'Поддержка',
    'mission.title': 'Наша Миссия',
    'mission.description': 'В Borderless Wellbeing мы верим, что доступ к ресурсам психического и физического здоровья не должен иметь границ.',
    'features.title': 'Wellness Без Границ',
    'features.subtitle': 'Откройте для себя наш комплексный набор функций, разработанных для поддержки вашего путешествия к лучшему здоровью и благополучию.',
    'footer.company': 'Wellness Без Границ',
    'footer.description': 'Соединяя глобальные сообщества для продвижения психического и физического благополучия без границ.'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
